#ifndef _MHAL_HW_PQ_ST_H_
#define _MHAL_HW_PQ_ST_H_

#define SUPPORT_HDMI_HDR_PERFRAME_DS		(TRUE)
//#define HDR10_DOLBY

#define BYTE_PER_WORD				(32)//MIU 128: 16Byte/W, MIU 256: 32Byte/W
#define EMP_DMA_MEM_BASE_UNIT			BYTE_PER_WORD
#define HDMI_SHM_EMP_DMA_MEM_SIZE		0x1280//memory for emp dma
#define HDMI_SHM_EMP_DMA_MEM_NUM_MAX		3//3frame
#define HDMI_SHM_EMP_DMA_MEM_SIZE_MAX		(HDMI_SHM_EMP_DMA_MEM_SIZE * HDMI_SHM_EMP_DMA_MEM_NUM_MAX)//0x1280 * 3frame = 0x3780 for EM Packet DMA
#define HDMI_SHM_EMP_DMA_THRESHOLD		0x1F

//Ver 1 Only 3 packet use HW, others use SW to do the CRC and DESCRAMBLE
//Ver 2 All packet use HW crc and DESCRAMBLE
//Ver 3 Add HDMI 2.1 EM packets process
#define XC_DOLBY_CRC_DESCRAMBLE_VER		(3)
#define XC_HDR_DOLBY_PACKET_LENGTH		(128)//128 byte
#define XC_HDR_DOLBY_PACKET_HEADER		(3)
#define XC_HDR_DOLBY_PACKET_TAIL		(4)
#define XC_HDR_DOLBY_METADATA_LENGTH_BIT	(2)// 2 front bytes of dolby packet body is metadata length
#define XC_HDR_HW_SUPPORT_MAX_DOLBY_PACKET	(8)
#define XC_DOLBY_PACKET_REPEAT_NUM		(3)
#define XC_DOLBY_PACKET_SRAM_NUM		(XC_DOLBY_PACKET_REPEAT_NUM * XC_HDR_HW_SUPPORT_MAX_DOLBY_PACKET)
#define XC_DOLBY_PACKET_SRAM_LENGTH		(XC_HDR_DOLBY_PACKET_LENGTH * XC_HDR_HW_SUPPORT_MAX_DOLBY_PACKET * XC_DOLBY_PACKET_REPEAT_NUM)
#define XC_DOLBY_FIRST_PACKET_REMAIN_MAX_LENGTH	(XC_HDR_DOLBY_PACKET_LENGTH - XC_HDR_DOLBY_PACKET_HEADER - XC_HDR_DOLBY_PACKET_TAIL - XC_HDR_DOLBY_METADATA_LENGTH_BIT)
#define XC_DOLBY_OTHER_PACKET_REMAIN_MAX_LENGTH	(XC_HDR_DOLBY_PACKET_LENGTH - XC_HDR_DOLBY_PACKET_HEADER - XC_HDR_DOLBY_PACKET_TAIL)
#define DOLBY_FORCE_CRCERROR_COUNT		(5)

#define DOLBY_GD_ENABLE				1

#endif		//_MHAL_HW_PQ_ST_H_