#
# Makefile for MStar GFLIP HAL drivers.
#

# general options
#EXTRA_CFLAGS      +=  -Idrivers/mstar/common
EXTRA_CFLAGS      +=  -Idrivers/mstar/include
EXTRA_CFLAGS      +=  -Idrivers/mstar/gflip/drv
EXTRA_CFLAGS      +=  -Idrivers/mstar/gflip/drv/mt5896

# files
obj-y             += mhal_gflip.o
