#ifndef HWREG_SRCCAP_HDMIRX_STRUCT_H
#define  HWREG_SRCCAP_HDMIRX_STRUCT_H


enum HDMI_AUDIO_PATH_TYPE
{
	HDMI_AUDIO_PATH0 = 0,
	HDMI_AUDIO_PATH1,
	HDMI_AUDIO_PATH2,
	HDMI_AUDIO_PATH3,
	HDMI_AUDIO_PATH_MAX,
	HDMI_AUDIO_PATH_NONE,
};

enum HDMI_DVI2MIU_PATH_TYPE
{
	HDMI_DVI2MIU_PATH0 = 0,
	HDMI_DVI2MIU_PATH1,
	HDMI_DVI2MIU_PATH2,
	HDMI_DVI2MIU_PATH3,
	HDMI_DVI2MIU_PATH_MAX,
	HDMI_DVI2MIU_PATH_NONE,
};

enum E_DVI2MIU_MUX {
	DVI2MIU_S0,
	DVI2MIU_S1,
	DVI2MIU_MAX,
};

typedef enum
{
    E_SIG_TMDS,
    E_SIG_FRL,
    E_SIG_CR_NO_LOCK,
}EN_HDMI_SIGNAL_TYPE;


enum hdmi_param_query_type{
	E_HDMI_PARM_HW_DEF,
	E_HDMI_PARM_SW_PROG,
	E_HDMI_PARM_HW_DEF_AND_SW_PROG,
};

enum hdmi_hw_parameter_list {
	E_HDMI_MAC_DIVIDER_N,
	E_HDMI_PHY_DIVIDER_N,
	E_HDMI_FRL_DTOP_2_MAC_P_N,
	E_HDMI_TMDS_DTOP_2_MAC_P_N,
	E_HDMI_FRL_MAC_P_N,
	E_HDMI_TMDS_MAC_P_N,
	E_HDMI_IMMESWITCH_E,
	E_HDMI_SRAM_PD_E,
	E_HDMI_420_2XCLK_E,
	E_HDMI_422_2_444_BYPASS_E,
	E_HDMI_PKTQ_E,
	E_HDMI_R2_E,
	E_HDMI_VIDEO_N,
	E_HDMI_AUDIO_N,
	E_HDMI_DVI2MIU_N,
	E_HDMI_DSC_N,
	E_HDMI_DRAM_OFS_R2LOAD, // unit 0x20
	E_HDMI_DRAM_OFS_PKTQ,
	E_HDMI_DRAM_OFS_DVI2MIU,
	E_HDMI_DRAM_OFS_END,
	E_HDMI_PARAM_N,
};

enum E_MAC_TOP_ISR_EVT {
	E_DEC_MISC_P0,
	E_DEC_MISC_P1,
	E_DEC_MISC_P2,
	E_DEC_MISC_P3,
	E_DEP_MISC_P0,
	E_DEP_MISC_P1,
	E_DEP_MISC_P2,
	E_DEP_MISC_P3,
	E_DTOP_MISC,
	E_INNER_MISC,
	E_DSCD,
	E_MAC_TOP_ISR_EVT_N,
};

#endif /* HWREG_SRCCAP_HDMIRX_STRUCT_H*/
