#
# Makefile for MStar CPU IO device drivers.
#

# general options
EXTRA_CFLAGS      +=  -I$(KERNEL_PATH_MSTAR2)/include
EXTRA_CFLAGS      +=  -I$(KERNEL_PATH_MSTAR2)/drv/cpu/arm64/generic/cpu_io

# specific options
EXTRA_CFLAGS      +=

# files
obj-y             += mdrv_cpu_io.o
