#
# Makefile for MStar R2 device drivers.
#
# general options
EXTRA_CFLAGS      +=  -Idrivers/soc/mediatek/tv/include
EXTRA_CFLAGS      +=  -Idrivers/soc/mediatek/tv/drv/r2
EXTRA_CFLAGS      +=  -Idrivers/soc/mediatek/tv/hal/mt5896/r2
EXTRA_CFLAGS      +=  -Iinclude/linux

obj-y   := mdrv_r2.o
obj-y   += mdrv_r2_io.o
obj-y    += ../../hal/mt5896/r2/mhal_r2.o
